[tool.black]
target-version = ['py36', 'py37', 'py38', 'py39', 'py310', 'py311']
skip-string-normalization = false
line-length = 88
include = '\.pyi?$'
exclude = '''
/(
    \.eggs
  | \.git
  | \.hg
  | \.mypy_cache
  | \.tox
  | \.venv
  | _build
  | buck-out
  | build
  | dist
  | __pycache__
  | .ipynb_checkpoints  # Exclude Jupyter Notebook checkpoints
)/
'''
